### ISSUE TITLE
local.ERROR: SQLSTATE[HY000]

### ISSUE THREAD

**Issue by m2ura** [lanhktc/s-cart#49]
On create product, SQL gives this error on version 3.3.0.3

Logs...

[2019-12-04 03:07:48] local.ERROR: SQLSTATE[HY000]: General error: 1364 Field 'sku' doesn't have a default value (SQL: insert into `shop_product` (`updated_at`, `created_at`) values (2019-12-04 03:07:44, 2019-12-04 03:07:44)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'sku' doesn't have a default value (SQL: insert into `shop_product` (`updated_at`, `created_at`) values (2019-12-04 03:07:44, 2019-12-04 03:07:44)) at /var/www/laravel/blackhat/vendor/laravel/framework/src/Illuminate/Database/Connection.php:665)
[stacktrace]
#0 /var/www/laravel/blackhat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(625): Illuminate\\Database\\Connection->runQueryCallback('insert into `sh...', Array, Object(Closure))
#1 /var/www/laravel/blackhat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(460): Illuminate\\Database\\Connection->run('insert into `sh...', Array, Object(Closure))
#2 /var/www/laravel/blackhat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(412): Illuminate\\Database\\Connection->statement('insert into `sh...', Array)

**Comment by lanhktc** [comment]
For hotfix, you can read https://github.com/lanhktc/s-cart/commit/e111e9feb500fa43d1ff610e0053e65b7b83b4a8
This error will fix in relase 3.3.0.4
